# Generated by Django 5.2.15 on 2026-07-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_reference", models.CharField(blank=True, max_length=128)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("email", "email"),
                            ("pdf", "pdf"),
                            ("excel", "excel"),
                            ("csv", "csv"),
                            ("rfq", "rfq"),
                            ("rfq-attachment", "rfq-attachment"),
                            ("pasted-text", "pasted-text"),
                            ("manual", "manual"),
                            ("sample", "sample"),
                        ],
                        max_length=32,
                    ),
                ),
                ("received_at", models.DateTimeField()),
                (
                    "requested_delivery_date",
                    models.CharField(blank=True, max_length=32),
                ),
                ("delivery_location", models.CharField(blank=True, max_length=255)),
                ("currency", models.CharField(max_length=8)),
                ("field_status", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("extracted", "extracted"),
                            ("review-needed", "review-needed"),
                            ("blocked", "blocked"),
                            ("ready", "ready"),
                            ("erp-ready", "erp-ready"),
                        ],
                        max_length=32,
                    ),
                ),
                ("customer_profile", models.JSONField(blank=True, default=dict)),
                ("source_document_summary", models.TextField(blank=True)),
                ("original_excerpt", models.TextField(blank=True)),
                ("ground_truth", models.JSONField(blank=True, default=dict)),
                ("covered_edge_cases", models.JSONField(blank=True, default=list)),
                ("is_simulated", models.BooleanField(default=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("original_text", models.TextField()),
                ("normalized_name", models.CharField(blank=True, max_length=255)),
                ("normalized_attributes", models.JSONField(blank=True, default=dict)),
                ("quantity", models.FloatField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pcs", "pcs"),
                            ("ea", "ea"),
                            ("m", "m"),
                            ("mm", "mm"),
                            ("cm", "cm"),
                            ("kg", "kg"),
                            ("g", "g"),
                            ("l", "l"),
                            ("set", "set"),
                            ("box", "box"),
                            ("pack", "pack"),
                            ("unknown", "unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("requested_sku", models.CharField(blank=True, max_length=128)),
                ("customer_part_number", models.CharField(blank=True, max_length=128)),
                ("unit_price", models.FloatField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unprocessed", "unprocessed"),
                            ("normalized", "normalized"),
                            ("matched", "matched"),
                            ("review-needed", "review-needed"),
                            ("blocked", "blocked"),
                            ("no-match", "no-match"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "selected_match_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="matching.matchcandidate",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="orders.orderrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="OrderException",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("missing-unit", "missing-unit"),
                            ("ambiguous-sku", "ambiguous-sku"),
                            ("low-confidence", "low-confidence"),
                            ("no-catalog-match", "no-catalog-match"),
                            ("discontinued-item", "discontinued-item"),
                            ("price-mismatch", "price-mismatch"),
                            ("duplicate-line", "duplicate-line"),
                            ("delivery-ambiguity", "delivery-ambiguity"),
                            (
                                "required-erp-field-missing",
                                "required-erp-field-missing",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("review", "review"),
                            ("blocking", "blocking"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("resolved", "resolved"),
                            ("ignored", "ignored"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("blocks_erp_readiness", models.BooleanField(default=False)),
                ("recovery_action", models.TextField(blank=True)),
                (
                    "line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions",
                        to="orders.orderlineitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="orders.orderrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadinessCheck",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "passed"),
                            ("review-needed", "review-needed"),
                            ("blocked", "blocked"),
                            ("unavailable", "unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("related_line_item_ids", models.JSONField(blank=True, default=list)),
                ("related_exception_ids", models.JSONField(blank=True, default=list)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_checks",
                        to="orders.orderrecord",
                    ),
                ),
            ],
        ),
    ]
