# Generated by Django 5.2.15 on 2026-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrecord",
            name="order_number",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
