# Generated by Django 5.2.15 on 2026-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("sku", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                (
                    "manufacturer_part_number",
                    models.CharField(blank=True, max_length=128),
                ),
                ("customer_part_numbers", models.JSONField(blank=True, default=list)),
                ("attributes", models.JSONField(blank=True, default=list)),
                (
                    "default_unit",
                    models.CharField(
                        choices=[
                            ("pcs", "pcs"),
                            ("ea", "ea"),
                            ("m", "m"),
                            ("mm", "mm"),
                            ("cm", "cm"),
                            ("kg", "kg"),
                            ("g", "g"),
                            ("l", "l"),
                            ("set", "set"),
                            ("box", "box"),
                            ("pack", "pack"),
                            ("unknown", "unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("price_amount", models.FloatField(blank=True, null=True)),
                ("price_currency", models.CharField(blank=True, max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("discontinued", "discontinued"),
                            ("replacement-available", "replacement-available"),
                            ("unknown", "unknown"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("replacement_sku", models.CharField(blank=True, max_length=128)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
