# Generated by Django 5.2.15 on 2026-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogitem",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="embedding_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
