# Generated by Django 5.2.15 on 2026-07-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                            ("deferred", "deferred"),
                        ],
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                ("is_simulated", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchCandidate",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("sku", models.CharField(blank=True, max_length=128)),
                (
                    "confidence_band",
                    models.CharField(
                        choices=[
                            ("high-confidence", "high-confidence"),
                            ("review-needed", "review-needed"),
                            ("blocked", "blocked"),
                            ("no-match", "no-match"),
                        ],
                        max_length=32,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField()),
                ("proof_items", models.JSONField(blank=True, default=list)),
                ("missing_evidence", models.JSONField(blank=True, default=list)),
                ("conflicting_evidence", models.JSONField(blank=True, default=list)),
                ("requires_human_review", models.BooleanField(default=False)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_candidates",
                        to="catalogs.catalogitem",
                    ),
                ),
            ],
            options={
                "ordering": ["line_item", "rank"],
            },
        ),
    ]
