# Generated by Django 5.2.15 on 2026-07-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchcandidate",
            name="line_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_candidates",
                to="orders.orderlineitem",
            ),
        ),
        migrations.AddField(
            model_name="matchdecision",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="matching.matchcandidate",
            ),
        ),
        migrations.AddField(
            model_name="matchdecision",
            name="line_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="orders.orderlineitem",
            ),
        ),
    ]
