# Generated by Django 5.2.15 on 2026-07-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchdecision",
            name="custom_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="matchdecision",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="matching.matchcandidate",
            ),
        ),
    ]
