# Generated by Django 5.2.15 on 2026-07-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_matchdecision_custom_label_and_more"),
        ("orders", "0003_orderrecord_demo_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchcandidate",
            name="learned_signal",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="CustomerPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demo_session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("customer_key", models.CharField(db_index=True, max_length=128)),
                ("normalized_request", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=128)),
                ("times_chosen", models.PositiveIntegerField(default=0)),
                ("times_rejected", models.PositiveIntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-times_chosen", "sku"],
                "indexes": [
                    models.Index(
                        fields=[
                            "demo_session_id",
                            "customer_key",
                            "normalized_request",
                        ],
                        name="matching_cu_demo_se_551e72_idx",
                    )
                ],
                "unique_together": {
                    ("demo_session_id", "customer_key", "normalized_request", "sku")
                },
            },
        ),
        migrations.CreateModel(
            name="CustomerCorrection",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "demo_session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("customer_key", models.CharField(db_index=True, max_length=128)),
                ("customer_name", models.CharField(max_length=255)),
                ("request_text", models.TextField()),
                ("normalized_request", models.CharField(db_index=True, max_length=255)),
                ("suggested_sku", models.CharField(blank=True, max_length=128)),
                ("chosen_sku", models.CharField(blank=True, max_length=128)),
                ("custom_label", models.CharField(blank=True, max_length=255)),
                ("chosen_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("was_correction", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="orders.orderrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["demo_session_id", "customer_key"],
                        name="matching_cu_demo_se_9675cf_idx",
                    )
                ],
            },
        ),
    ]
