# Generated by Django 5.2.15 on 2026-07-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0004_matchcandidate_learned_signal_customerpreference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerContextFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demo_session_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("customer_key", models.CharField(db_index=True, max_length=128)),
                ("customer_name", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("built_from_corrections", models.PositiveIntegerField(default=0)),
                ("edited_by_human", models.BooleanField(default=False)),
                ("generated_by", models.CharField(default="agent", max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("demo_session_id", "customer_key")},
            },
        ),
    ]
