# Generated by Django 5.2.15 on 2026-07-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SetupConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_approve_threshold", models.FloatField(default=85)),
                ("price_flag_threshold", models.FloatField(default=15)),
                ("stop_discontinued_items", models.BooleanField(default=True)),
                ("review_noncatalog_items", models.BooleanField(default=True)),
                ("flag_duplicate_lines", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
