# Generated by Django 5.2.15 on 2026-07-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnboardingSetup",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "catalog_item_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_simulated", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_rules",
                        to="onboarding.onboardingsetup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("catalog-ingestion", "catalog-ingestion"),
                            ("field-mapping", "field-mapping"),
                            ("customer-rules", "customer-rules"),
                            ("eval-baseline", "eval-baseline"),
                            ("readiness-checks", "readiness-checks"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not-started", "not-started"),
                            ("in-progress", "in-progress"),
                            ("complete", "complete"),
                            ("blocked", "blocked"),
                            ("requires-review", "requires-review"),
                        ],
                        max_length=32,
                    ),
                ),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="onboarding.onboardingsetup",
                    ),
                ),
            ],
            options={
                "ordering": ["setup", "id"],
            },
        ),
        migrations.CreateModel(
            name="SetupConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_approve_threshold", models.FloatField(default=85)),
                ("price_flag_threshold", models.FloatField(default=15)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "setup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="onboarding.onboardingsetup",
                    ),
                ),
            ],
        ),
    ]
