# Generated by Django 5.2.15 on 2026-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setupconfiguration",
            name="demo_session_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
    ]
