import {
  AlertTriangle,
  ArrowRight,
  CheckCircle2,
  CircleDashed,
  Clock3,
  Database,
  ExternalLink,
  FileSearch,
  ListChecks,
  Loader2,
  Mail,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  ShieldCheck,
  Sun,
  XCircle,
} from "lucide-react";

export const icons = {
  action: ArrowRight,
  blocked: XCircle,
  database: Database,
  error: AlertTriangle,
  externalLink: ExternalLink,
  loading: Loader2,
  mail: Mail,
  moon: Moon,
  orderReview: FileSearch,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  pending: CircleDashed,
  readiness: ListChecks,
  review: Clock3,
  success: CheckCircle2,
  sun: Sun,
  trust: ShieldCheck,
} as const;

export type IconName = keyof typeof icons;
